name: podcast_summarizer # The name of your app
description: A Flutter app to summarize podcasts. # A short description of your app
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1 # Version of your app (format: versionNumber+buildNumber)

environment:
  sdk: '>=3.0.0 <4.0.0' # Flutter SDK version constraint

dependencies:
  flutter:
    sdk: flutter
  http: ^0.15.0 # For making HTTP requests
  flutter_local_notifications: ^14.0.0 # For local notifications
  provider: ^6.0.0 # For state management
  mongo_dart: ^0.10.0 # For MongoDB integration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # For linting and code analysis

flutter:
  uses-material-design: true